name: Tests

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: PHP syntax check
        run: composer lint

      - name: PHP_CodeSniffer
        run: composer phpcs

      - name: PHPUnit
        run: composer test

      - name: Version consistency
        run: composer check-version
